config/routes.rb
Rails.application.routes.draw do
  devise_for :administradoras
  root 'application#index'

  namespace :api do
    resources :categorias, only: [:index, :show]
    resources :relevamientos, only: [:index,:create,:update,:show] do
      resources :comentarios, only: [:index, :create]
    end
    resources :instancias, only: [:create]
    post 'instancias/login', to: 'instancias#login'
    resources :subscripciones, only: [:create]
  end

  namespace :panel do
    get '/', to: 'administradoras#index'

    resources :subscripciones, only: [:index]
    get :'extras/historico', to: 'extras#historico'
    resources :extras, only: [:index, :show] do
      post :deshacer, to: 'extras#deshacer'
    end

    resources :administradoras do
      post :unlock, to: 'administradoras#unlock'
      post :lock, to: 'administradoras#lock'
      post :super, to: 'administradoras#super'
      post :unsuper, to: 'administradoras#unsuper'
    end

    resources :grupos
    get 'categorias/orden', to: 'categorias#orden'
    post 'categorias/reordenar', to: 'categorias#reordenar'
    resources :categorias do
      get 'plantillas/orden', to: 'plantillas#orden'
      post 'plantillas/reordenar', to: 'plantillas#reordenar'
    end
    resources :instancias

    resources :relevamientos do
      post :confirm, to: 'relevamientos#confirm'
      resources :comentarios
    end
  end
end

app/models/administradora.rb
class Administradora < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :lockable

  has_many :comentarios, as: :comentarista
  has_and_belongs_to_many :grupos
  has_many :administradoras, through: :grupos
  has_many :categorias, through: :grupos

  def to_s
    email.split('@').first
  end

  def super!
    self.update_attribute :super, true
  end

  def unsuper!
    self.update_attribute :super, false
  end
end

app/controllers/panel/administradoras_controller.rb
class Panel::AdministradorasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    authorize Administradora
    @administradoras = policy_scope(Administradora)
  end

  def new
    authorize Administradora
    @administradora = Administradora.new
  end

  # Cuando creamos una administradora, no elegimos la contraseña sino
  # que le enviamos el correo de recuperación para que se elija una
  def create
    authorize Administradora
    @administradora = Administradora.new administradora_params
    @administradora.password = SecureRandom.hex

    if @administradora.save
      @administradora.send_reset_password_instructions
    end

    respond_with :panel, @administradora
  end

  # no necesitamos ver una pagina con el mail solamente
  def show
    redirect_to panel_administradoras_path
  end

  def destroy
    find_administradora
    authorize @administradora

    @administradora.destroy
    if @administradora == current_administradora
      sign_out
    else
      respond_with :panel, @administradora
    end
  end

  def edit
    find_administradora
    authorize @administradora
  end

  # Si cambiamos el mail le enviamos una notificacion
  def update
    find_administradora
    authorize @administradora

    @administradora.update_attributes administradora_params

    if @administradora.email_changed?
      @administradora.send_email_changed_notification
    end

    respond_with :panel, @administradora
  end

  def lock
    find_administradora
    authorize @administradora
    @administradora.lock_access! send_instructions: false

    respond_with :panel, @administradora
  end

  def unlock
    find_administradora
    authorize @administradora
    @administradora.unlock_access!

    respond_with :panel, @administradora
  end

  def super
    find_administradora
    authorize @administradora
    @administradora.super!

    respond_with :panel, @administradora
  end

  def unsuper
    find_administradora
    authorize @administradora
    @administradora.unsuper!

    respond_with :panel, @administradora
  end

  private

  def find_administradora
    @administradora = Administradora.find(params[:id] || params[:administradora_id])
  end

  def administradora_params
    params.require(:administradora).permit(:email, grupo_ids: [])
  end
end

app/controllers/panel/categorias_controller.rb
class Panel::CategoriasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    @categorias = policy_scope(Categoria)
  end

  def orden
    authorize Categoria
    if params[:categoria].blank?
      @categorias = Categoria.where(raiz_id: nil)
    else
      @categoria = Categoria.find(params[:categoria])
      @categorias = Categoria.where(raiz_id: params[:categoria])
    end
  end

  # Reordenar las categorías y subcategorías
  #
  # Al reordenar las categorías, necesitamos ubicar sub categorías justo
  # debajo de la categoría, recursivamente.
  def reordenar
    authorize Categoria
    p = params[:categorias][:orden]

    # Encontrar todas las categorías a ordenar, pueden ser raíz o sub
    # categorías o sub sub categorias
    @categorias = Categoria.where(id: p.keys)
    # Ejecutar dentro de una sola transacción
    Categoria.transaction do
      # Recorrerlas todas
      @categorias.each do |c|
        # Actualizar el orden a partir de la raíz y convertimos a un
        # decimal dentro de ese orden
        orden = if c.raiz
          c.raiz.orden + (p[c.id.to_s].to_f + 1.0) / Categoria::SUB_BASE
        # O si no hay raíz, usar un número entero.  Sumamos uno para no
        # empezar de 0
        else
          p[c.id.to_s].to_f + 1.0
        end

        # Actualizamos el orden
        c.update_attribute :orden, orden
        # Y también actualizamos el orden de las sub categorías
        c.sub_categorias.order(:orden).each_with_index do |s,i|
          s.update_attribute :orden, orden + (i.to_f + 1.0) / Categoria::SUB_BASE
        end
      end
    end

    redirect_to_filters_or panel_categorias_path
  end

  def new
    authorize Categoria
    @categoria = Categoria.new
    @categoria.raiz_id = params[:raiz] if params[:raiz].present?

    @categoria.color = "#%06x" % (rand * 0xffffff)
    @categoria.plantillas.build
  end

  def create
    authorize Categoria
    @categoria = Categoria.create categoria_params

    respond_with :panel, @categoria
  end

  # Por ahora no queremos ver ninguna categoría individual
  def show
    redirect_to_filters_or panel_categorias_path
  end

  def destroy
    find_categoria
    authorize @categoria
    @categoria.destroy
    respond_with :panel, @categoria
  end

  def edit
    find_categoria
    authorize @categoria

    @categoria.plantillas.build if @categoria.plantillas.empty?
  end

  def update
    find_categoria
    authorize @categoria
    @categoria.update_attributes categoria_params
    respond_with :panel, @categoria
  end

  private

  def categoria_params
    params
      .require(:categoria)
      .permit(:raiz_id, :nombre, :color, :descripcion, :confidencial,
        plantillas_attributes: [:id, :_destroy, :label, :help,
          :required, :photo, :value, :multiple, possible_values: [] ])
  end

  def find_categoria
    @categoria = Categoria.find(params[:id] || params[:categoria_id])
  end
end

app/controllers/panel/comentarios_controller.rb
class Panel::ComentariosController < ApplicationController
  before_action :authenticate_administradora!

  def create
    authorize Comentario
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.create(comentario_params)
    @comentario.comentarista = current_administradora

    @comentario.save

    redirect_to [:panel,@relevamiento]
  end

  def edit
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario
  end

  def update
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario

    @comentario.update_attributes comentario_params

    redirect_to [:panel, @relevamiento]
  end

  def destroy
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario

    @comentario.destroy

    redirect_to [:panel, @relevamiento]
  end

  private
  def comentario_params
    params.require(:comentario).permit(:contenido, :privado)
  end
end

app/controllers/panel/extras_controller.rb
require 'csv'

class Panel::ExtrasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html, :csv, :geojson

  def index
    authorize Extra
    @q = policy_scope(Extra).includes(:plantilla, :instancia, relevamiento: [ :categoria ]).ransack(params[:q])
    @extras = @q.result
    @historico = params[:historico].present?

    respond_to do |f|
      f.html do
        @extras = @extras.page(params[:page])
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"extras.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }
        @headers = %w[id log_version relevamiento.categoria.arbol
          relevamiento.instancia.short_identifier relevamiento.id
          plantilla.label valor created_at updated_at]

        render layout: false
      end
    end
  end

  def historico
    authorize Extra
    @q = policy_scope(Extra).unscoped.includes(:plantilla, :instancia, relevamiento: [ :categoria ]).ransack(params[:q])
    # Agrupar los extras por relevamiento.  Ya vienen agrupados por
    # plantilla así que no es necesario.
    @extras = @q.result.sort_by do |e|
      e.plantilla.order
    end.group_by do |e|
      e.relevamiento_id
    end
    # Necesitamos saber la fecha mayor y menor
    @from = @q.result.order(:created_at).try(:first).try(:created_at)
    @to   = @q.result.order(:updated_at).try(:last).try(:updated_at)
    begin
      @range = (@from.try(:to_date)..@to.try(:to_date)).to_a
    rescue ArgumentError, TypeError
      @range = []
    end

    respond_to do |f|
      f.html do
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"historico.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @headers = %w[relevamiento_id plantilla.label]
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }

        render layout: false
      end

      f.geojson do
        features = []

        # TODO esta algoritmo se repite por cada vista...
        @extras.each do |grupo|
          grupo.try(:last).try(:each) do |extra|
            attributes = {
              t('.relevamiento_id') => grupo.try(:first),
              t('.plantilla.label') => extra.try(:plantilla).try(:label)
            }.merge(
              Hash[@range.map do |date|
                [date, if extra.try(:updated_at).try(:to_date) == date
                  extra.try(:valor)
                else
                  extra.at(time: date).try(:valor)
                end]
              end])
            features << RGeo::GeoJSON::Feature.new(extra.relevamiento.coordenadas, extra.id, attributes)
          end
        end

        collection = RGeo::GeoJSON::FeatureCollection.new(features)

        render json: RGeo::GeoJSON.encode(collection)
      end
    end
  end

  def show
    @extra = policy_scope(Extra).find(params[:id])
    authorize @extra
  end

  def deshacer
    @extra = policy_scope(Extra).find(params[:extra_id])
    authorize @extra

    if @extra.switch_to! params[:version].to_i
      flash[:success] = t('.undo_success')
    else
      flash[:warning] = t('.undo_error')
    end

    redirect_to panel_extra_path(@extra)
  end
end

app/controllers/panel/grupos_controller.rb
class Panel::GruposController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    @grupos = policy_scope(Grupo)
  end

  def new
    authorize Grupo
    @grupo = Grupo.new
  end

  def create
    authorize Grupo
    @grupo = Grupo.create(grupo_params)

    respond_with :panel, @grupo
  end

  def show
    authorize Grupo
    @grupo = Grupo.find(params[:id])
  end

  def edit
    authorize Grupo
    @grupo = Grupo.find(params[:id])
  end

  def update
    authorize Grupo
    @grupo = Grupo.find(params[:id])
    @grupo.update_attributes(grupo_params)

    respond_with :panel, @grupo
  end

  def destroy
    authorize Grupo
    @grupo = Grupo.find(params[:id])
    @grupo.destroy

    respond_with :panel, @grupo
  end

  private

  def grupo_params
    params.require(:grupo).permit(:nombre, administradora_ids: [], categoria_ids: [])
  end

end

app/controllers/panel/instancias_controller.rb
class Panel::InstanciasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    authorize Instancia
    @q = policy_scope(Instancia).ransack(params[:q])
    @instancias = @q.result.page(params[:page])
  end

  def destroy
    @instancia = Instancia.find(params[:id])
    authorize @instancia
    @instancia.destroy

    redirect_to_filters_or panel_instancias_path
  end

  def new
    authorize Instancia

    @instancia = Instancia.new
  end

  def create
    authorize Instancia
    @instancia = Instancia.new(instancia_params)

    if @instancia.save
      redirect_to_filters_or panel_instancias_path
    else
      render 'panel/instancias/new'
    end
  end

  def edit
    @instancia = Instancia.find(params[:instancia_id] || params[:id])
    authorize @instancia
  end

  def update
    @instancia = Instancia.find(params[:instancia_id] || params[:id])
    authorize @instancia

    if @instancia.save
      redirect_to_filters_or panel_instancias_path
    else
      render 'panel/instancias/edit'
    end
  end

  private

  def instancia_params
    params.require(:instancia).permit(:identifier, :password)
  end
end

app/controllers/panel/plantillas_controller.rb
class Panel::PlantillasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def orden
    @categoria = Categoria.find(params[:categoria_id])
    authorize @categoria, :ordenar_plantillas?
    @plantillas = @categoria.plantillas
  end

  def reordenar
    @categoria = Categoria.find(params[:categoria_id])
    authorize @categoria, :ordenar_plantillas?
    @plantillas = @categoria.plantillas

    order = params.require(:plantillas).permit(order: {})
    Plantilla.transaction do
      @plantillas.each do |p|
        p.update_attribute :order, order[:order][p.id.to_s]
      end
    end

    redirect_to_filters_or panel_categoria_plantillas_orden_path(@categoria)
  end
end

app/controllers/panel/subscripciones_controller.rb
require 'csv'

class Panel::SubscripcionesController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html, :csv

  def index
    authorize Subscripcion
    @subscripciones = Subscripcion.all

    respond_to do |f|
      f.html do
        @subscripciones = @subscripciones.page(params[:page])
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"subscripciones.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }
        @headers = %w[id email created_at]

        render layout: false
      end
    end
  end
end

app/views/panel/administradoras/_form.haml
= form_for [:panel, @administradora] do |f|
  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control'
  .form-group
    = f.label :grupo_ids
    = f.collection_select :grupo_ids, policy_scope(Grupo),
      :id, :to_s, {include_blank: true},
      {class: 'form-control select-2', placeholder: t('.prompt'), multiple: true}
  .form-group
    = f.submit t('administradoras.new'), class: 'btn btn-success'

app/views/panel/administradoras/edit.haml
.row
  .col
    = render 'panel/nav'
.row
  .col
    %h1= @administradora.email

    = render 'panel/administradoras/form'

app/views/panel/administradoras/index.haml
.row
  .col
    = render 'panel/nav'
.row
  .col
    %h1= t('panel.administradoras.title')

    %table.table.table-condensed.table-striped
      %thead
        %tr
          %th #
          %th= fa_icon 'users', title: t('.super')
          %th= t('administradoras.email')
          %th
      %tfoot
        %tr
          %td{colspan: 4}
            - if policy(Administradora).new?
              = link_to new_panel_administradora_path,
                class: 'btn btn-success' do
                = fa_icon 'plus'
                = t('administradoras.new')
      %tbody
        - @administradoras.each do |admin|  
          %tr
            %td= admin.id
            %td
              - unless admin.super?
                = fa_icon 'users', title: t('.super')
            %td
              - if admin.access_locked?
                = fa_icon 'lock', title: t('administradoras.locked')
                %span.sr-only= t('administradoras.locked')
              - if admin == current_administradora
                %strong= admin.email
              - else
                = admin.email
            %td
              .btn-group{role: 'group', aria: { label: t('administradoras.actions') }}
                - if policy(admin).edit?
                  = link_to edit_panel_administradora_path(admin),
                    class: 'btn btn-info' do
                    = fa_icon 'edit'
                    %span.sr-only= t('administradoras.edit')
                - if policy(admin).lock?
                  - if admin.access_locked?
                    = link_to panel_administradora_unlock_path(admin),
                      method: :post,
                      data: { confirm: t('administradoras.unlock.confirm') },
                      class: 'btn btn-secondary' do
                      = fa_icon 'unlock', title: t('administradoras.unlock.button')
                      %span.sr-only= t('administradoras.unlock.button')
                  - else
                    = link_to panel_administradora_lock_path(admin),
                      method: :post,
                      data: { confirm: t('administradoras.lock.confirm') },
                      class: 'btn btn-warning' do
                      = fa_icon 'lock', title: t('administradoras.lock.button')
                      %span.sr-only= t('administradoras.lock.button')
                - if policy(admin).super?
                  = link_to panel_administradora_unsuper_path(admin),
                    method: :post,
                    data: { confirm: t('.to_unsuper') },
                    class: 'btn btn-success' do
                    = fa_icon 'users', title: t('.to_unsuper')
                - elsif policy(admin).unsuper?
                  = link_to panel_administradora_super_path(admin),
                    method: :post,
                    data: { confirm: t('.to_super') },
                    class: 'btn btn-warning' do
                    = fa_icon 'user', title: t('.to_super')
                - if policy(admin).destroy?
                  = link_to panel_administradora_path(admin), method: :delete,
                    class: 'btn btn-danger',
                    data: { confirm: t('administradoras.delete.confirm') } do
                    = fa_icon 'remove'
                    %span.sr-only= t('administradoras.delete.button')

app/views/panel/administradoras/new.haml
.row
  .col
    = render 'panel/nav'
.row
  .col
    %h1= t('administradoras.new')

    = render 'panel/administradoras/form'