config/routes.rb
Rails.application.routes.draw do
  devise_for :administradoras
  root 'application#index'

  namespace :api do
    resources :categorias, only: [:index, :show]
    resources :relevamientos, only: [:index,:create,:update,:show] do
      resources :comentarios, only: [:index, :create]
    end
    resources :instancias, only: [:create]
    post 'instancias/login', to: 'instancias#login'
    resources :subscripciones, only: [:create]
  end

  namespace :panel do
    get '/', to: 'administradoras#index'

    resources :subscripciones, only: [:index]
    get :'extras/historico', to: 'extras#historico'
    resources :extras, only: [:index, :show] do
      post :deshacer, to: 'extras#deshacer'
    end

    resources :administradoras do
      post :unlock, to: 'administradoras#unlock'
      post :lock, to: 'administradoras#lock'
      post :super, to: 'administradoras#super'
      post :unsuper, to: 'administradoras#unsuper'
    end

    resources :grupos
    get 'categorias/orden', to: 'categorias#orden'
    post 'categorias/reordenar', to: 'categorias#reordenar'
    resources :categorias do
      get 'plantillas/orden', to: 'plantillas#orden'
      post 'plantillas/reordenar', to: 'plantillas#reordenar'
    end
    resources :instancias

    resources :relevamientos do
      post :confirm, to: 'relevamientos#confirm'
      resources :comentarios
    end
  end
end

app/models/categoria.rb
class Categoria < ApplicationRecord
  has_many :relevamientos, dependent: :restrict_with_error
  has_many :plantillas, dependent: :restrict_with_error
  belongs_to :raiz, class_name: 'Categoria', optional: true
  has_many :sub_categorias, class_name: 'Categoria', foreign_key: 'raiz_id'
  has_and_belongs_to_many :grupos

  validates_presence_of :nombre

  accepts_nested_attributes_for :plantillas, allow_destroy: true

  before_save :update_arbol!
  before_save :ordenar_plantillas!
  after_save :update_arbol_in_sub_categorias!

  default_scope -> { order(:orden) }

  SUB_BASE = 1000000.freeze

  def to_s
    arbol
  end

  def update_arbol!
    self.arbol = raiz.present? ? "#{raiz} / #{nombre}" : nombre
  end

  def update_arbol_in_sub_categorias!
    sub_categorias.map(&:update_arbol!)
    sub_categorias.map(&:save)
  end

  def total
    relevamientos_count + (sub_categorias.pluck(:relevamientos_count).inject(:+) || 0)
  end

  def arbol_con_total
    "#{arbol} (#{total})"
  end

  def ordenar_plantillas!
    plantillas.each_with_index do |plantilla, index|
      plantilla.order = index
    end

    true
  end
end

app/controllers/api/categorias_controller.rb
class Api::CategoriasController < Api::BaseController
  def index
    # Rescatamos los fallos de autenticación porque queremos mostrar las
    # confidenciales solo a las instancias, no por un tema de seguridad
    # porque cualquiera puede registrar una instancia, sino para
    # diferenciar momentos en que se pueden ver y momentos en los que
    # no.
    begin
      authenticate_token
      render json: serialize(Categoria.all.includes(:sub_categorias))
    # XXX no estamos usando todas estas excepciones en
    # Api::BaseController pero las dejamos para el futuro.
    rescue ExceptionHandler::AuthenticationError,
      ExceptionHandler::MissingToken,
      ExceptionHandler::InvalidToken,
      ExceptionHandler::ExpiredSignature,
      ExceptionHandler::DecodeError
      render json: serialize(Categoria.where(confidencial: false))
    end
  end

  def show
    @categoria = Categoria.find(params[:id])

    if @categoria
      render json: serialize(@categoria, { include: [ :plantillas ] })
    else
      render json: {}, status: :notfound
    end
  end

  private

  def serialize(categoria, options = {})
    CategoriaSerializer.new(categoria, options).serialized_json
  end
end

app/controllers/panel/administradoras_controller.rb
class Panel::AdministradorasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    authorize Administradora
    @administradoras = policy_scope(Administradora)
  end

  def new
    authorize Administradora
    @administradora = Administradora.new
  end

  # Cuando creamos una administradora, no elegimos la contraseña sino
  # que le enviamos el correo de recuperación para que se elija una
  def create
    authorize Administradora
    @administradora = Administradora.new administradora_params
    @administradora.password = SecureRandom.hex

    if @administradora.save
      @administradora.send_reset_password_instructions
    end

    respond_with :panel, @administradora
  end

  # no necesitamos ver una pagina con el mail solamente
  def show
    redirect_to panel_administradoras_path
  end

  def destroy
    find_administradora
    authorize @administradora

    @administradora.destroy
    if @administradora == current_administradora
      sign_out
    else
      respond_with :panel, @administradora
    end
  end

  def edit
    find_administradora
    authorize @administradora
  end

  # Si cambiamos el mail le enviamos una notificacion
  def update
    find_administradora
    authorize @administradora

    @administradora.update_attributes administradora_params

    if @administradora.email_changed?
      @administradora.send_email_changed_notification
    end

    respond_with :panel, @administradora
  end

  def lock
    find_administradora
    authorize @administradora
    @administradora.lock_access! send_instructions: false

    respond_with :panel, @administradora
  end

  def unlock
    find_administradora
    authorize @administradora
    @administradora.unlock_access!

    respond_with :panel, @administradora
  end

  def super
    find_administradora
    authorize @administradora
    @administradora.super!

    respond_with :panel, @administradora
  end

  def unsuper
    find_administradora
    authorize @administradora
    @administradora.unsuper!

    respond_with :panel, @administradora
  end

  private

  def find_administradora
    @administradora = Administradora.find(params[:id] || params[:administradora_id])
  end

  def administradora_params
    params.require(:administradora).permit(:email, grupo_ids: [])
  end
end

app/controllers/panel/categorias_controller.rb
class Panel::CategoriasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    @categorias = policy_scope(Categoria)
  end

  def orden
    authorize Categoria
    if params[:categoria].blank?
      @categorias = Categoria.where(raiz_id: nil)
    else
      @categoria = Categoria.find(params[:categoria])
      @categorias = Categoria.where(raiz_id: params[:categoria])
    end
  end

  # Reordenar las categorías y subcategorías
  #
  # Al reordenar las categorías, necesitamos ubicar sub categorías justo
  # debajo de la categoría, recursivamente.
  def reordenar
    authorize Categoria
    p = params[:categorias][:orden]

    # Encontrar todas las categorías a ordenar, pueden ser raíz o sub
    # categorías o sub sub categorias
    @categorias = Categoria.where(id: p.keys)
    # Ejecutar dentro de una sola transacción
    Categoria.transaction do
      # Recorrerlas todas
      @categorias.each do |c|
        # Actualizar el orden a partir de la raíz y convertimos a un
        # decimal dentro de ese orden
        orden = if c.raiz
          c.raiz.orden + (p[c.id.to_s].to_f + 1.0) / Categoria::SUB_BASE
        # O si no hay raíz, usar un número entero.  Sumamos uno para no
        # empezar de 0
        else
          p[c.id.to_s].to_f + 1.0
        end

        # Actualizamos el orden
        c.update_attribute :orden, orden
        # Y también actualizamos el orden de las sub categorías
        c.sub_categorias.order(:orden).each_with_index do |s,i|
          s.update_attribute :orden, orden + (i.to_f + 1.0) / Categoria::SUB_BASE
        end
      end
    end

    redirect_to_filters_or panel_categorias_path
  end

  def new
    authorize Categoria
    @categoria = Categoria.new
    @categoria.raiz_id = params[:raiz] if params[:raiz].present?

    @categoria.color = "#%06x" % (rand * 0xffffff)
    @categoria.plantillas.build
  end

  def create
    authorize Categoria
    @categoria = Categoria.create categoria_params

    respond_with :panel, @categoria
  end

  # Por ahora no queremos ver ninguna categoría individual
  def show
    redirect_to_filters_or panel_categorias_path
  end

  def destroy
    find_categoria
    authorize @categoria
    @categoria.destroy
    respond_with :panel, @categoria
  end

  def edit
    find_categoria
    authorize @categoria

    @categoria.plantillas.build if @categoria.plantillas.empty?
  end

  def update
    find_categoria
    authorize @categoria
    @categoria.update_attributes categoria_params
    respond_with :panel, @categoria
  end

  private

  def categoria_params
    params
      .require(:categoria)
      .permit(:raiz_id, :nombre, :color, :descripcion, :confidencial,
        plantillas_attributes: [:id, :_destroy, :label, :help,
          :required, :photo, :value, :multiple, possible_values: [] ])
  end

  def find_categoria
    @categoria = Categoria.find(params[:id] || params[:categoria_id])
  end
end

app/controllers/panel/comentarios_controller.rb
class Panel::ComentariosController < ApplicationController
  before_action :authenticate_administradora!

  def create
    authorize Comentario
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.create(comentario_params)
    @comentario.comentarista = current_administradora

    @comentario.save

    redirect_to [:panel,@relevamiento]
  end

  def edit
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario
  end

  def update
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario

    @comentario.update_attributes comentario_params

    redirect_to [:panel, @relevamiento]
  end

  def destroy
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario

    @comentario.destroy

    redirect_to [:panel, @relevamiento]
  end

  private
  def comentario_params
    params.require(:comentario).permit(:contenido, :privado)
  end
end

app/controllers/panel/extras_controller.rb
require 'csv'

class Panel::ExtrasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html, :csv, :geojson

  def index
    authorize Extra
    @q = policy_scope(Extra).includes(:plantilla, :instancia, relevamiento: [ :categoria ]).ransack(params[:q])
    @extras = @q.result
    @historico = params[:historico].present?

    respond_to do |f|
      f.html do
        @extras = @extras.page(params[:page])
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"extras.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }
        @headers = %w[id log_version relevamiento.categoria.arbol
          relevamiento.instancia.short_identifier relevamiento.id
          plantilla.label valor created_at updated_at]

        render layout: false
      end
    end
  end

  def historico
    authorize Extra
    @q = policy_scope(Extra).unscoped.includes(:plantilla, :instancia, relevamiento: [ :categoria ]).ransack(params[:q])
    # Agrupar los extras por relevamiento.  Ya vienen agrupados por
    # plantilla así que no es necesario.
    @extras = @q.result.sort_by do |e|
      e.plantilla.order
    end.group_by do |e|
      e.relevamiento_id
    end
    # Necesitamos saber la fecha mayor y menor
    @from = @q.result.order(:created_at).try(:first).try(:created_at)
    @to   = @q.result.order(:updated_at).try(:last).try(:updated_at)
    begin
      @range = (@from.try(:to_date)..@to.try(:to_date)).to_a
    rescue ArgumentError, TypeError
      @range = []
    end

    respond_to do |f|
      f.html do
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"historico.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @headers = %w[relevamiento_id plantilla.label]
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }

        render layout: false
      end

      f.geojson do
        features = []

        # TODO esta algoritmo se repite por cada vista...
        @extras.each do |grupo|
          grupo.try(:last).try(:each) do |extra|
            attributes = {
              t('.relevamiento_id') => grupo.try(:first),
              t('.plantilla.label') => extra.try(:plantilla).try(:label)
            }.merge(
              Hash[@range.map do |date|
                [date, if extra.try(:updated_at).try(:to_date) == date
                  extra.try(:valor)
                else
                  extra.at(time: date).try(:valor)
                end]
              end])
            features << RGeo::GeoJSON::Feature.new(extra.relevamiento.coordenadas, extra.id, attributes)
          end
        end

        collection = RGeo::GeoJSON::FeatureCollection.new(features)

        render json: RGeo::GeoJSON.encode(collection)
      end
    end
  end

  def show
    @extra = policy_scope(Extra).find(params[:id])
    authorize @extra
  end

  def deshacer
    @extra = policy_scope(Extra).find(params[:extra_id])
    authorize @extra

    if @extra.switch_to! params[:version].to_i
      flash[:success] = t('.undo_success')
    else
      flash[:warning] = t('.undo_error')
    end

    redirect_to panel_extra_path(@extra)
  end
end

app/controllers/panel/grupos_controller.rb
class Panel::GruposController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    @grupos = policy_scope(Grupo)
  end

  def new
    authorize Grupo
    @grupo = Grupo.new
  end

  def create
    authorize Grupo
    @grupo = Grupo.create(grupo_params)

    respond_with :panel, @grupo
  end

  def show
    authorize Grupo
    @grupo = Grupo.find(params[:id])
  end

  def edit
    authorize Grupo
    @grupo = Grupo.find(params[:id])
  end

  def update
    authorize Grupo
    @grupo = Grupo.find(params[:id])
    @grupo.update_attributes(grupo_params)

    respond_with :panel, @grupo
  end

  def destroy
    authorize Grupo
    @grupo = Grupo.find(params[:id])
    @grupo.destroy

    respond_with :panel, @grupo
  end

  private

  def grupo_params
    params.require(:grupo).permit(:nombre, administradora_ids: [], categoria_ids: [])
  end

end

app/controllers/panel/instancias_controller.rb
class Panel::InstanciasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    authorize Instancia
    @q = policy_scope(Instancia).ransack(params[:q])
    @instancias = @q.result.page(params[:page])
  end

  def destroy
    @instancia = Instancia.find(params[:id])
    authorize @instancia
    @instancia.destroy

    redirect_to_filters_or panel_instancias_path
  end

  def new
    authorize Instancia

    @instancia = Instancia.new
  end

  def create
    authorize Instancia
    @instancia = Instancia.new(instancia_params)

    if @instancia.save
      redirect_to_filters_or panel_instancias_path
    else
      render 'panel/instancias/new'
    end
  end

  def edit
    @instancia = Instancia.find(params[:instancia_id] || params[:id])
    authorize @instancia
  end

  def update
    @instancia = Instancia.find(params[:instancia_id] || params[:id])
    authorize @instancia

    if @instancia.save
      redirect_to_filters_or panel_instancias_path
    else
      render 'panel/instancias/edit'
    end
  end

  private

  def instancia_params
    params.require(:instancia).permit(:identifier, :password)
  end
end

app/controllers/panel/plantillas_controller.rb
class Panel::PlantillasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def orden
    @categoria = Categoria.find(params[:categoria_id])
    authorize @categoria, :ordenar_plantillas?
    @plantillas = @categoria.plantillas
  end

  def reordenar
    @categoria = Categoria.find(params[:categoria_id])
    authorize @categoria, :ordenar_plantillas?
    @plantillas = @categoria.plantillas

    order = params.require(:plantillas).permit(order: {})
    Plantilla.transaction do
      @plantillas.each do |p|
        p.update_attribute :order, order[:order][p.id.to_s]
      end
    end

    redirect_to_filters_or panel_categoria_plantillas_orden_path(@categoria)
  end
end

app/controllers/panel/subscripciones_controller.rb
require 'csv'

class Panel::SubscripcionesController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html, :csv

  def index
    authorize Subscripcion
    @subscripciones = Subscripcion.all

    respond_to do |f|
      f.html do
        @subscripciones = @subscripciones.page(params[:page])
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"subscripciones.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }
        @headers = %w[id email created_at]

        render layout: false
      end
    end
  end
end

app/views/panel/categorias/_fila.haml
%tr
  %td
    %div.color{style: "background-color: #{categoria.color};"}
  %td
    - if categoria.confidencial?
      = fa_icon 'lock', title: t('.confidencial')
    = categoria.arbol
    %br/
    %small.text-muted= categoria.descripcion
    %br/
    %small.text-muted= categoria.grupos.map(&:to_s).join(', ')
  %td= categoria.relevamientos_count
  %td= categoria.total
  %td
    .btn-group{role: 'group', aria: { label: t('.actions') }}
      - if policy(categoria).edit?
        = link_to edit_panel_categoria_path(categoria), class: 'btn btn-info' do
          = fa_icon 'edit', title: t('.edit')
          %span.sr-only= t('.edit')
        = link_to new_panel_categoria_path(raiz: categoria.id), class: 'btn btn-success' do
          = fa_icon 'plus', title: t('.sub')
          %span.sr-only= t('.sub')
      - if policy(categoria).orden?
        - unless categoria.sub_categoria_ids.empty?
          = link_to panel_categorias_orden_path(categoria: categoria.id), class: 'btn btn-success' do
            = fa_icon 'indent', title: t('.orden')
            %span.sr-only= t('.orden')
      - if policy(categoria).ordenar_plantillas?
        = link_to panel_categoria_plantillas_orden_path(categoria), class: 'btn btn-info' do
          = fa_icon 'reorder', title: t('.plantillas.orden')
          %span.sr-only= t('.plantillas.orden')
      - if policy(categoria).destroy?
        = link_to panel_categoria_path(categoria), method: :delete,
          data: { confirm: t('.delete.confirm') },
          class: 'btn btn-danger' do
          = fa_icon 'remove', title: t('.delete.button')
          %span.sr-only= t('.delete.button')

app/views/panel/categorias/_form.haml
= form_for [:panel,@categoria] do |f|
  .form-group
    - if params[:raiz].present?
      = f.label :raiz
      = f.collection_select :raiz_id,
        policy_scope(Categoria).where.not(id: @categoria.id), :id, :to_s,
        { prompt: t('.prompt'), include_blank: t('.none') },
        { class: 'form-control' }
  .form-group
    = f.label :nombre
    = f.text_field :nombre, class: 'form-control'
  .form-group
    = f.label :descripcion
    = f.text_area :descripcion, class: 'form-control'
  .form-group
    = f.label :color
    = f.color_field :color, class: 'form-control'
  .form-group
    = f.label :confidencial
    = f.check_box :confidencial, class: 'form-control'
  %h2
    = t('.plantillas')
  .field-groups.plantillas
    = link_to '#', class: 'add-group btn btn-success', data: { group: 'plantillas' } do
      = fa_icon 'plus'
      = t('.plantilla.add')
    = f.fields_for :plantillas do |p|
      - id = 'plantillas-'+(p.object.id || Time.now.to_i).to_s
      .field-group{id: id, class: p.object.new_record? ? 'new' : ''}
        = link_to '#', class: 'plantillas remove-group btn btn-danger pull-right' do
          = fa_icon 'close', title: t('.plantilla.remove')
        = p.hidden_field :_destroy
        = p.hidden_field :id
        .row
          .col
            .form-group
              = p.label :label
              = p.text_field :label, class: 'form-control'
          .col
            .form-group
              = p.label :value
              - options = Plantilla::VALUES.map { |value| [t('.plantilla.'+value), value] }
              = p.select :value, options, {}, { class: 'form-control',
                onchange: 'window.toggle_possible_values(this)' }
        .row.possible-values{class: (p.object.value == 'select' ? '' : 'd-none')}
          .col
            .form-group
              = p.label :possible_values
              = p.select :possible_values, (p.object.possible_values || []),
                {},
                { class: 'form-control select-2',
                  placeholder: t('.possible_values'),
                  data: { tags: true },
                  multiple: true }
          .col
            .form-group
              = p.label :multiple
              .form-check
                = p.check_box :multiple, class: 'form-check-input'
                = p.label :multiple, t('.plantilla.multiple')
        .row
          .col
            .form-check.form-check-inline
              = p.check_box :photo, class: 'form-check-input'
              = p.label :photo
            .form-check.form-check-inline
              = p.check_box :required, class: 'form-check-input'
              = p.label :required

        .row
          .col
            .form-group
              = p.label :help
              = p.text_area :help, class: 'form-control'
        %hr/
  .form-group
    = f.submit t('.submit'), class: 'btn btn-success'

app/views/panel/categorias/edit.haml
.row
  .col
    = render 'panel/nav'

.row
  .col
    %h1= @categoria

    = render 'panel/categorias/form'

app/views/panel/categorias/index.haml
.row
  .col
    = render 'panel/nav'

.row
  .col
    %h1= t('.title')

    - if policy(Categoria).new?
      = link_to new_panel_categoria_path,
        class: 'btn btn-success' do
        = fa_icon 'plus'
        = t('.new')
    - if policy(Categoria).orden?
      = link_to panel_categorias_orden_path,
        class: 'btn btn-info' do
        = fa_icon 'sort'
        = t('.orden')

    %table.table.table-condensed.table-striped
      %thead
        %tr
          - th = %w[.color .nombre .relevamientos .total]
          - th.each do |h|
            %th= t(h)
          %th
      %tfoot
        %tr
          %td{colspan: th.count + 1}
      %tbody
        - @categorias.each do |c|
          = render 'panel/categorias/fila', categoria: c

app/views/panel/categorias/new.haml
.row
  .col
    = render 'panel/nav'

.row
  .col
    %h1= t('.title')

    = render 'panel/categorias/form'

app/views/panel/categorias/orden.haml
.row
  .col
    = render 'panel/nav'

.row
  .col
    %h1
      = t('.title')
      - if @categoria
        = @categoria.nombre
    %p= t('.description')

    = form_tag panel_categorias_reordenar_path, method: :post do
      %table.table.table-condensed.table-striped.table-draggable
        %thead
          %tr
            - th = %w[.orden .nombre]
            - th.each do |h|
              %th= t(h)
        %tfoot
          %tr
            %td{colspan: th.count}
              - if policy(Categoria).reordenar?
                = submit_tag t('.reorder'), class: 'btn btn-success'
        %tbody
          - @categorias.each do |categoria|
            %tr
              %td
                = fa_icon 'arrows-v', class: 'handle'
                = hidden_field 'categorias[orden]', categoria.id,
                  value: categoria.orden, class: 'field order'
              %td
                - if categoria.confidencial?
                  = fa_icon 'lock', title: t('.confidencial')
                - if categoria.sub_categorias.count > 1
                  = link_to categoria.arbol, panel_categorias_orden_path(categoria: categoria.id)
                - else
                  = categoria.arbol
                %br/
                %small.text-muted= categoria.descripcion