config/routes.rb
Rails.application.routes.draw do
  devise_for :administradoras
  root 'application#index'

  namespace :api do
    resources :categorias, only: [:index, :show]
    resources :relevamientos, only: [:index,:create,:update,:show] do
      resources :comentarios, only: [:index, :create]
    end
    resources :instancias, only: [:create]
    post 'instancias/login', to: 'instancias#login'
    resources :subscripciones, only: [:create]
  end

  namespace :panel do
    get '/', to: 'administradoras#index'

    resources :subscripciones, only: [:index]
    get :'extras/historico', to: 'extras#historico'
    resources :extras, only: [:index, :show] do
      post :deshacer, to: 'extras#deshacer'
    end

    resources :administradoras do
      post :unlock, to: 'administradoras#unlock'
      post :lock, to: 'administradoras#lock'
      post :super, to: 'administradoras#super'
      post :unsuper, to: 'administradoras#unsuper'
    end

    resources :grupos
    get 'categorias/orden', to: 'categorias#orden'
    post 'categorias/reordenar', to: 'categorias#reordenar'
    resources :categorias do
      get 'plantillas/orden', to: 'plantillas#orden'
      post 'plantillas/reordenar', to: 'plantillas#reordenar'
    end
    resources :instancias

    resources :relevamientos do
      post :confirm, to: 'relevamientos#confirm'
      resources :comentarios
    end
  end
end

app/controllers/panel/administradoras_controller.rb
class Panel::AdministradorasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    authorize Administradora
    @administradoras = policy_scope(Administradora)
  end

  def new
    authorize Administradora
    @administradora = Administradora.new
  end

  # Cuando creamos una administradora, no elegimos la contraseña sino
  # que le enviamos el correo de recuperación para que se elija una
  def create
    authorize Administradora
    @administradora = Administradora.new administradora_params
    @administradora.password = SecureRandom.hex

    if @administradora.save
      @administradora.send_reset_password_instructions
    end

    respond_with :panel, @administradora
  end

  # no necesitamos ver una pagina con el mail solamente
  def show
    redirect_to panel_administradoras_path
  end

  def destroy
    find_administradora
    authorize @administradora

    @administradora.destroy
    if @administradora == current_administradora
      sign_out
    else
      respond_with :panel, @administradora
    end
  end

  def edit
    find_administradora
    authorize @administradora
  end

  # Si cambiamos el mail le enviamos una notificacion
  def update
    find_administradora
    authorize @administradora

    @administradora.update_attributes administradora_params

    if @administradora.email_changed?
      @administradora.send_email_changed_notification
    end

    respond_with :panel, @administradora
  end

  def lock
    find_administradora
    authorize @administradora
    @administradora.lock_access! send_instructions: false

    respond_with :panel, @administradora
  end

  def unlock
    find_administradora
    authorize @administradora
    @administradora.unlock_access!

    respond_with :panel, @administradora
  end

  def super
    find_administradora
    authorize @administradora
    @administradora.super!

    respond_with :panel, @administradora
  end

  def unsuper
    find_administradora
    authorize @administradora
    @administradora.unsuper!

    respond_with :panel, @administradora
  end

  private

  def find_administradora
    @administradora = Administradora.find(params[:id] || params[:administradora_id])
  end

  def administradora_params
    params.require(:administradora).permit(:email, grupo_ids: [])
  end
end

app/controllers/panel/categorias_controller.rb
class Panel::CategoriasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    @categorias = policy_scope(Categoria)
  end

  def orden
    authorize Categoria
    if params[:categoria].blank?
      @categorias = Categoria.where(raiz_id: nil)
    else
      @categoria = Categoria.find(params[:categoria])
      @categorias = Categoria.where(raiz_id: params[:categoria])
    end
  end

  # Reordenar las categorías y subcategorías
  #
  # Al reordenar las categorías, necesitamos ubicar sub categorías justo
  # debajo de la categoría, recursivamente.
  def reordenar
    authorize Categoria
    p = params[:categorias][:orden]

    # Encontrar todas las categorías a ordenar, pueden ser raíz o sub
    # categorías o sub sub categorias
    @categorias = Categoria.where(id: p.keys)
    # Ejecutar dentro de una sola transacción
    Categoria.transaction do
      # Recorrerlas todas
      @categorias.each do |c|
        # Actualizar el orden a partir de la raíz y convertimos a un
        # decimal dentro de ese orden
        orden = if c.raiz
          c.raiz.orden + (p[c.id.to_s].to_f + 1.0) / Categoria::SUB_BASE
        # O si no hay raíz, usar un número entero.  Sumamos uno para no
        # empezar de 0
        else
          p[c.id.to_s].to_f + 1.0
        end

        # Actualizamos el orden
        c.update_attribute :orden, orden
        # Y también actualizamos el orden de las sub categorías
        c.sub_categorias.order(:orden).each_with_index do |s,i|
          s.update_attribute :orden, orden + (i.to_f + 1.0) / Categoria::SUB_BASE
        end
      end
    end

    redirect_to_filters_or panel_categorias_path
  end

  def new
    authorize Categoria
    @categoria = Categoria.new
    @categoria.raiz_id = params[:raiz] if params[:raiz].present?

    @categoria.color = "#%06x" % (rand * 0xffffff)
    @categoria.plantillas.build
  end

  def create
    authorize Categoria
    @categoria = Categoria.create categoria_params

    respond_with :panel, @categoria
  end

  # Por ahora no queremos ver ninguna categoría individual
  def show
    redirect_to_filters_or panel_categorias_path
  end

  def destroy
    find_categoria
    authorize @categoria
    @categoria.destroy
    respond_with :panel, @categoria
  end

  def edit
    find_categoria
    authorize @categoria

    @categoria.plantillas.build if @categoria.plantillas.empty?
  end

  def update
    find_categoria
    authorize @categoria
    @categoria.update_attributes categoria_params
    respond_with :panel, @categoria
  end

  private

  def categoria_params
    params
      .require(:categoria)
      .permit(:raiz_id, :nombre, :color, :descripcion, :confidencial,
        plantillas_attributes: [:id, :_destroy, :label, :help,
          :required, :photo, :value, :multiple, possible_values: [] ])
  end

  def find_categoria
    @categoria = Categoria.find(params[:id] || params[:categoria_id])
  end
end

app/controllers/panel/comentarios_controller.rb
class Panel::ComentariosController < ApplicationController
  before_action :authenticate_administradora!

  def create
    authorize Comentario
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.create(comentario_params)
    @comentario.comentarista = current_administradora

    @comentario.save

    redirect_to [:panel,@relevamiento]
  end

  def edit
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario
  end

  def update
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario

    @comentario.update_attributes comentario_params

    redirect_to [:panel, @relevamiento]
  end

  def destroy
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario

    @comentario.destroy

    redirect_to [:panel, @relevamiento]
  end

  private
  def comentario_params
    params.require(:comentario).permit(:contenido, :privado)
  end
end

app/controllers/panel/extras_controller.rb
require 'csv'

class Panel::ExtrasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html, :csv, :geojson

  def index
    authorize Extra
    @q = policy_scope(Extra).includes(:plantilla, :instancia, relevamiento: [ :categoria ]).ransack(params[:q])
    @extras = @q.result
    @historico = params[:historico].present?

    respond_to do |f|
      f.html do
        @extras = @extras.page(params[:page])
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"extras.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }
        @headers = %w[id log_version relevamiento.categoria.arbol
          relevamiento.instancia.short_identifier relevamiento.id
          plantilla.label valor created_at updated_at]

        render layout: false
      end
    end
  end

  def historico
    authorize Extra
    @q = policy_scope(Extra).unscoped.includes(:plantilla, :instancia, relevamiento: [ :categoria ]).ransack(params[:q])
    # Agrupar los extras por relevamiento.  Ya vienen agrupados por
    # plantilla así que no es necesario.
    @extras = @q.result.sort_by do |e|
      e.plantilla.order
    end.group_by do |e|
      e.relevamiento_id
    end
    # Necesitamos saber la fecha mayor y menor
    @from = @q.result.order(:created_at).try(:first).try(:created_at)
    @to   = @q.result.order(:updated_at).try(:last).try(:updated_at)
    begin
      @range = (@from.try(:to_date)..@to.try(:to_date)).to_a
    rescue ArgumentError, TypeError
      @range = []
    end

    respond_to do |f|
      f.html do
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"historico.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @headers = %w[relevamiento_id plantilla.label]
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }

        render layout: false
      end

      f.geojson do
        features = []

        # TODO esta algoritmo se repite por cada vista...
        @extras.each do |grupo|
          grupo.try(:last).try(:each) do |extra|
            attributes = {
              t('.relevamiento_id') => grupo.try(:first),
              t('.plantilla.label') => extra.try(:plantilla).try(:label)
            }.merge(
              Hash[@range.map do |date|
                [date, if extra.try(:updated_at).try(:to_date) == date
                  extra.try(:valor)
                else
                  extra.at(time: date).try(:valor)
                end]
              end])
            features << RGeo::GeoJSON::Feature.new(extra.relevamiento.coordenadas, extra.id, attributes)
          end
        end

        collection = RGeo::GeoJSON::FeatureCollection.new(features)

        render json: RGeo::GeoJSON.encode(collection)
      end
    end
  end

  def show
    @extra = policy_scope(Extra).find(params[:id])
    authorize @extra
  end

  def deshacer
    @extra = policy_scope(Extra).find(params[:extra_id])
    authorize @extra

    if @extra.switch_to! params[:version].to_i
      flash[:success] = t('.undo_success')
    else
      flash[:warning] = t('.undo_error')
    end

    redirect_to panel_extra_path(@extra)
  end
end

app/controllers/panel/grupos_controller.rb
class Panel::GruposController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    @grupos = policy_scope(Grupo)
  end

  def new
    authorize Grupo
    @grupo = Grupo.new
  end

  def create
    authorize Grupo
    @grupo = Grupo.create(grupo_params)

    respond_with :panel, @grupo
  end

  def show
    authorize Grupo
    @grupo = Grupo.find(params[:id])
  end

  def edit
    authorize Grupo
    @grupo = Grupo.find(params[:id])
  end

  def update
    authorize Grupo
    @grupo = Grupo.find(params[:id])
    @grupo.update_attributes(grupo_params)

    respond_with :panel, @grupo
  end

  def destroy
    authorize Grupo
    @grupo = Grupo.find(params[:id])
    @grupo.destroy

    respond_with :panel, @grupo
  end

  private

  def grupo_params
    params.require(:grupo).permit(:nombre, administradora_ids: [], categoria_ids: [])
  end

end

app/controllers/panel/instancias_controller.rb
class Panel::InstanciasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    authorize Instancia
    @q = policy_scope(Instancia).ransack(params[:q])
    @instancias = @q.result.page(params[:page])
  end

  def destroy
    @instancia = Instancia.find(params[:id])
    authorize @instancia
    @instancia.destroy

    redirect_to_filters_or panel_instancias_path
  end

  def new
    authorize Instancia

    @instancia = Instancia.new
  end

  def create
    authorize Instancia
    @instancia = Instancia.new(instancia_params)

    if @instancia.save
      redirect_to_filters_or panel_instancias_path
    else
      render 'panel/instancias/new'
    end
  end

  def edit
    @instancia = Instancia.find(params[:instancia_id] || params[:id])
    authorize @instancia
  end

  def update
    @instancia = Instancia.find(params[:instancia_id] || params[:id])
    authorize @instancia

    if @instancia.save
      redirect_to_filters_or panel_instancias_path
    else
      render 'panel/instancias/edit'
    end
  end

  private

  def instancia_params
    params.require(:instancia).permit(:identifier, :password)
  end
end

app/controllers/panel/plantillas_controller.rb
class Panel::PlantillasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def orden
    @categoria = Categoria.find(params[:categoria_id])
    authorize @categoria, :ordenar_plantillas?
    @plantillas = @categoria.plantillas
  end

  def reordenar
    @categoria = Categoria.find(params[:categoria_id])
    authorize @categoria, :ordenar_plantillas?
    @plantillas = @categoria.plantillas

    order = params.require(:plantillas).permit(order: {})
    Plantilla.transaction do
      @plantillas.each do |p|
        p.update_attribute :order, order[:order][p.id.to_s]
      end
    end

    redirect_to_filters_or panel_categoria_plantillas_orden_path(@categoria)
  end
end

app/controllers/panel/relevamientos_controller.rb
require 'csv'

class Panel::RelevamientosController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html, :csv, :geojson

  def index
    authorize Relevamiento
    @q = policy_scope(Relevamiento).ransack(params[:q])
    @relevamientos = @q.result
    # Los extras solo se muestran si estamos filtrando por categoría
    @extras = params[:extras].present? && params[:q][:categoria_id_eq].present?
    # Las subcategorías se incluyen opcionalmente
    @sub_categorias = params[:sub_categorias].present? && params[:q][:categoria_id_eq].present?
    @categoria = Categoria.find(params[:q][:categoria_id_eq]) if @extras || @sub_categorias

    @relevamientos = @relevamientos.includes(:extras) if @extras

    if @sub_categorias
      @relevamientos = @relevamientos.or(Relevamiento.where(categoria_id: @categoria.sub_categoria_ids))
    end

    @relevamientos = @relevamientos.includes(:instancia, :comentarios, categoria: [ :plantillas ])

    respond_to do |f|
      f.html do
        @relevamientos = @relevamientos.page(params[:page])
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"relevamientos.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }
        @headers = %w[id coordenadas.lat coordenadas.lon categoria.arbol
          categoria.color confirmado direccion descripcion
          informacion_de_contacto comentarios_to_plain_text foto_url
          created_at updated_at]

        render layout: false
      end

      # XXX Qué tan pesado será esto?
      f.geojson do
        features = []
        @relevamientos.each do |r|
          extras = {}
          if @extras
            extras = Hash[r.extras.map { |e| [e.plantilla.label, e.valor] }]
          end

          features << RGeo::GeoJSON::Feature.new(r.coordenadas, r.id,
            r.attributes
             .merge({ color: r.categoria.color,
                      categoria: r.categoria.arbol,
                      comentarios: r.comentarios_to_plain_text.split("\n")})
             .merge(extras))
        end
        collection = RGeo::GeoJSON::FeatureCollection.new(features)

        render json: RGeo::GeoJSON.encode(collection)

      end
    end
  end

  def show
    @relevamiento = Relevamiento.find(params[:id])
    authorize @relevamiento
  end

  def confirm
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    authorize @relevamiento
    @relevamiento.update_attribute :confirmado, true

    redirect_to_filters_or panel_relevamiento_path(@relevamiento)
  end

  def destroy
    @relevamiento = Relevamiento.find(params[:id])
    authorize @relevamiento
    @relevamiento.destroy

    redirect_to_filters_or panel_relevamiento_path(@relevamiento)
  end

  def edit
    @relevamiento = Relevamiento.find(params[:id])
    authorize @relevamiento
  end

  def update
    @relevamiento = Relevamiento.find(params[:id])
    authorize @relevamiento
    p = relevamiento_params
    coordenadas = Relevamiento.hash_to_wkt(p.delete(:coordenadas))
    p[:coordenadas] = coordenadas if coordenadas

    @relevamiento.update_attributes(p)

    redirect_to_filters_or panel_relevamiento_path(@relevamiento)
  end

  private

  def relevamiento_params
    params.require(:relevamiento).permit(:confirmado, :descripcion,
      :direccion, :informacion_de_contacto, :categoria_id,
      :remove_fotos,
      fotos: [],
      extras_attributes: [ :valor, :id ],
      coordenadas: {})
  end
end

app/views/panel/extras/_fila.haml
- q = params[:q] || {}
%tr
  %td= link_to extra.id, panel_extra_path(extra)
  %td
    - unless extra.fotos.empty?
      %a{href: extra.fotos.first.url}
        %img.img-small{src: extra.fotos.first.thumb.url }
  %td= link_to extra.relevamiento.categoria.arbol, panel_extras_path(q: q.merge({ relevamiento_categoria_id_eq: extra.relevamiento.categoria.id }), historico: params[:historico])
  %td= link_to extra.relevamiento.instancia.short_identifier, panel_extras_path(q: q.merge({ relevamiento_instancia_id_eq: extra.relevamiento.instancia.id }), historico: params[:historico])
  %td= link_to extra.relevamiento.id, panel_extras_path(q: q.merge({ relevamiento_id_eq: extra.relevamiento.id }), historico: params[:historico])
  %td= extra.try(:plantilla).try(:label)
  %td= extra.valor
  %td= extra.log_version
  %td= extra.created_at.strftime '%Y-%d-%m'
  %td= extra.updated_at.strftime '%Y-%d-%m'

app/views/panel/extras/historico.csv.erb
<%= "\xEF\xBB\xBF" %><%
# La grilla del CSV
csv = []

# Traer los campos seleccionados en el controlador
names = @headers.map do |h|
  t(".#{h}")
end

# Agregar todas las fechas
names = names + @range.map do |date|
  date.strftime('%F')
end

# Agregar los headers como primera fila
csv << names

# Procesar cada fila
@extras.each do |grupo|
  prev = nil
  grupo.try(:last).try(:each) do |extra|
    values = [grupo.try(:first),extra.try(:plantilla).try(:label)]
    csv << values + @range.map do |date|
      if extra.try(:updated_at).try(:to_date) == date
        valor = extra.try(:valor)
      else
        valor = extra.at(time: date).try(:valor)
      end

      unless prev == valor
        prev = valor
        valor
      end
    end
  end
end

# Imprimir todas las filas
csv.each do |row|
%><%=
  row.to_csv(@csv_options).html_safe
%><%
end
%>

app/views/panel/extras/historico.haml
.row
  .col
    = render 'panel/nav'
.row
  .col
    %h2= t('.filters')
    = search_form_for @q, url: panel_extras_historico_path do |f|
      .row
        .col
          .form-group
            = f.label :relevamiento_categoria_id_eq
            = f.collection_select :relevamiento_categoria_id_eq, policy_scope(Categoria),
              :id, :arbol_con_total, {include_blank: true},
              {class: 'form-control select-2', placeholder: t('.prompt')}
            %small.form-text.text-muted= t(".categoria_help")
        .col-md-4
          .form-group
            = f.label :relevamiento_confirmado_eq
            = f.select :relevamiento_confirmado_eq,
              options_for_select([[t('.yes'),1],[t('.no'),0]], params.try(:q).try(:relevamiento_confirmado_eq).try(:to_i)),
              {include_blank: true},
              {class: 'form-control select-2', placeholder: t('.prompt')}
      .row.align-items-end
        .col
          .form-group
            = f.label :relevamiento_descripcion_cont
            = f.text_field :relevamiento_descripcion_cont, class: 'form-control'
        .col
          .form-group
            = f.label :relevamiento_informacion_de_contacto_cont
            = f.text_field :relevamiento_informacion_de_contacto_cont, class: 'form-control'
        .col
          .form-group
            = f.label :relevamiento_direccion_cont
            = f.text_field :relevamiento_direccion_cont, class: 'form-control'
      .form-group
        .row
          .col
            %button.btn.btn-info.btn-block{type: 'submit'}
              = fa_icon 'search'
              = t('.filter')
          .col-md-2
            = link_to panel_extras_historico_path, class: 'btn btn-secondary' do
              = fa_icon 'remove'
              = t('.clear')
.row
  .col
    %h1
      = t('.title')
    .btn-group
      - [[:csv, 'table', 'success'], [:geojson,'map-o','info']].each do |f|
        = link_to panel_extras_historico_path(format: f.first,
          q: params[:q].try(:permit!)),
          class: "btn btn-#{f.last}" do
          = fa_icon f.second
          = t(".#{f.first.to_s}")

    %table.table.table-condensed.table-striped.table-responsive
      %thead
        %tr
          %th= t('.relevamiento_id')
          %th= t('.plantilla.label')
          - @range.each do |date|
            %th= date.strftime('%F')
      %tfoot
      %tbody
        - @extras.each do |grupo|
          - grupo.try(:last).try(:each) do |extra|
            %tr
              %th= grupo.try(:first)
              %th= extra.try(:plantilla).try(:label)
              - prev = nil
              - @range.each do |date|
                %td
                  - if extra.try(:updated_at).try(:to_date) == date
                    - valor = extra.try(:valor)
                  - else
                    - valor = extra.at(time: date).try(:valor)

                  = valor unless prev == valor
                  - prev = valor

app/views/panel/extras/index.csv.erb
<%= "\xEF\xBB\xBF" %><%=
@headers.map { |h| t(".#{h}") }.to_csv(@csv_options).html_safe
%><% 
@extras.to_a.uniq.each do |extra|
%><%=
@headers.map { |h| begin ; extra.instance_eval(h) ; rescue NoMethodError ; nil ; end}.to_csv(@csv_options).html_safe
%><%
if @historico && extra.log_size > 1
  extra.log_size.times do |version|
    e = extra.at(version: version)
    next unless e
%><%=
    @headers.map { |h| begin ; e.instance_eval(h) ; rescue NoMethodError ; nil ; end}.to_csv(@csv_options).html_safe
%><%
  end # version
end # historico
%><%
end # extras
%>

app/views/panel/extras/index.haml
- extras = @extras.to_a.uniq
.row
  .col
    = render 'panel/nav'
.row
  .col
    %h2= t('.filters')
    = search_form_for [:panel,@q] do |f|
      .row
        .col
          .form-group
            = f.label :relevamiento_categoria_id_eq
            = f.collection_select :relevamiento_categoria_id_eq, policy_scope(Categoria),
              :id, :arbol, {include_blank: true},
              {class: 'form-control select-2', placeholder: t('.prompt')}
          .form-group
            = f.label :plantilla_id_eq
            = f.select :plantilla_id_eq, Plantilla.pluck(:label, :id).uniq.compact.sort, {include_blank: true}, {class: 'form-control select-2'}
          .form-check.form-check-inline
            = check_box_tag :historico, 'true', params[:historico].present?, class: 'form-check-input'
            %label{for: 'historico'}= t('.historico')
      .form-group
        .row
          .col
            %button.btn.btn-info.btn-block{type: 'submit'}
              = fa_icon 'search'
              = t('.filter')
          .col-md-2
            = link_to panel_extras_path(page: params[:page].try(:permit!)), class: 'btn btn-secondary' do
              = fa_icon 'remove'
              = t('.clear')
.row
  .col
    %h1
      = t('.title')
      - q = extras.count
      - if @historico
        - q = extras.map(&:log_size).inject(:+)
      = t('.results', q: q)

    .btn-group
      - [[:csv, 'table', 'success']].each do |f|
        - params.permit!
        = link_to panel_extras_path(format: f.first,
          q: params[:q],
          historico: params[:historico]),
          class: "btn btn-#{f.last}" do
          = fa_icon f.second
          = t(".#{f.first.to_s}")
      = link_to t('.historico'), panel_extras_historico_path, class: 'btn btn-info'

    %table.table-striped.table.table-condensed.table-responsive
      %thead
        %tr
          %th
          %th= t('.foto')
          %th= sort_link(@q, :categoria, t('.categoria'))
          %th= sort_link(@q, :instancia, t('.instancia'))
          %th= sort_link(@q, :relevamiento, t('.relevamiento'))
          %th= sort_link(@q, :nombre, t('.nombre'))
          %th= sort_link(@q, :valor, t('.valor'))
          %th= t('.log_version')
          %th= sort_link(@q, :created_at, t('.created_at'))
          %th= sort_link(@q, :updated_at, t('.updated_at'))
      %tbody
        - extras.each do |extra|
          = render 'panel/extras/fila', extra: extra
          - if @historico && extra.log_size > 1
            - extra.log_size.times do |version|
              - e = extra.at(version: version)
              - next unless e
              = render 'panel/extras/fila', extra: e
    = paginate @extras, theme: 'twitter-bootstrap-4'

app/views/panel/extras/show.haml
.row
  .col
    = render 'panel/nav'
.row.justify-content-center
  .col-md-8
    = render 'layouts/flash'
    .card
      %img.card-img-top{src: @extra.fotos.first.try(:url) || '/default.png', alt: @extra.plantilla.try(:label)}
      .card-body
        %h5.card-title= @extra.plantilla.try(:label)
        %p.card-text= @extra.valor
        %p.card-text= @extra.updated_at
        %p.card-text
          = t('.revisiones')
          %span.badge.badge-primary= @extra.log_size

        - if @extra.log_size > 1
          %table.table.table-condensed.table-striped
            %thead
              %tr
                %th= t('.version')
                %th= t('.foto')
                %th= t('.nombre')
                %th= t('.valor')
                %th= t('.updated_at')
                %th= t('.instancia')
                %th
            %tfoot
            %tbody
              - @extra.log_size.times do |version|
                - extra = @extra.at(version: version)
                - next unless extra
                %tr
                  %td= version
                  %td
                    - if foto = extra.fotos.first.try(:thumb).try(:url)
                      = image_tag foto
                  %th= extra.plantilla.try(:label)
                  %td= extra.valor
                  %td= extra.updated_at
                  %td= extra.instancia.short_identifier
                  %td
                    = link_to panel_extra_deshacer_path(@extra, version: version), method: :post, class: 'btn btn-warning' do
                      = fa_icon 'undo'
                      = t('.deshacer')