config/routes.rb
Rails.application.routes.draw do
  devise_for :administradoras
  root 'application#index'

  namespace :api do
    resources :categorias, only: [:index, :show]
    resources :relevamientos, only: [:index,:create,:update,:show] do
      resources :comentarios, only: [:index, :create]
    end
    resources :instancias, only: [:create]
    post 'instancias/login', to: 'instancias#login'
    resources :subscripciones, only: [:create]
  end

  namespace :panel do
    get '/', to: 'administradoras#index'

    resources :subscripciones, only: [:index]
    get :'extras/historico', to: 'extras#historico'
    resources :extras, only: [:index, :show] do
      post :deshacer, to: 'extras#deshacer'
    end

    resources :administradoras do
      post :unlock, to: 'administradoras#unlock'
      post :lock, to: 'administradoras#lock'
      post :super, to: 'administradoras#super'
      post :unsuper, to: 'administradoras#unsuper'
    end

    resources :grupos
    get 'categorias/orden', to: 'categorias#orden'
    post 'categorias/reordenar', to: 'categorias#reordenar'
    resources :categorias do
      get 'plantillas/orden', to: 'plantillas#orden'
      post 'plantillas/reordenar', to: 'plantillas#reordenar'
    end
    resources :instancias

    resources :relevamientos do
      post :confirm, to: 'relevamientos#confirm'
      resources :comentarios
    end
  end
end

app/controllers/api/relevamientos_controller.rb
# Trabajar con relevamientos
class Api::RelevamientosController < Api::BaseController
  before_action :authenticate_token, only: [:create,:update]
  respond_to :json, :geojson
  # TODO: nunca devolver todos los puntos, siempre filtrarlos por zona
  # de búsqueda
  def index
    scope = Relevamiento.includes(:categoria)
    scope = scope.where(categoria_id: params[:categoria].split(',').compact.uniq) if params[:categoria].present?
    # Nunca se muestran los relevamientos confidenciales!
    scope = scope.where(categoria_id: Categoria.where(confidencial: false))

    respond_to do |format|
      format.json do
        render json: serialize(scope)
      end

      format.geojson do
        features = scope.map do |c|
          RGeo::GeoJSON::Feature.new c.coordenadas, c.id, { color: c.categoria.color }
        end
        collection = RGeo::GeoJSON::FeatureCollection.new features

        render json: RGeo::GeoJSON.encode(collection)
      end
    end
  end

  def show
    @relevamiento = Relevamiento.find(params[:id])

    if @relevamiento
      render json: serialize(@relevamiento, include: [:extras])
    else
      render json: {}, status: :notfound
    end
  end

  def create
    p = relevamiento_params
    c = p.delete :coordenadas
    e = p.delete :extra
    f = p.delete :fotos

    @relevamiento = @instancia.relevamientos.new(p)
    @relevamiento.coordenadas = Relevamiento.hash_to_wkt(c)
    fotos = process_fotos(f)
    @relevamiento.fotos = fotos['principal']
    @relevamiento.extras = process_extra(e, @instancia, fotos)

    if @relevamiento.save
      render json: serialize(@relevamiento), status: :created
    else
      render json: {}, status: :unprocessable_entity
    end

    delete_fotos(fotos)
  end

  # Cualquier instancia puede actualizar un relevamiento, pero queda un
  # historial gracias a logidze
  def update
    @relevamiento = Relevamiento.includes(extras: [ :plantilla ]).find(params[:data][:id])
    p = relevamiento_params
    # No se modifican las coordenadas así que no las necesitamos
    p.delete :coordenadas
    f = p.delete :fotos
    e = p.delete :extra

    # Las fotos se suman y los extra se mergean
    new_fotos = process_fotos(f)
    @relevamiento.fotos = new_fotos['principal'] unless new_fotos['principal'].blank?
    # Actualizar los valores si ya estaban definidos y también la
    # instancia para tener una cadena de responsabilidades.
    @relevamiento.extras.each do |extra|
      key = extra.plantilla.name
      new_valor = e[key]

      unless new_fotos[key].blank?
        extra.fotos = new_fotos[key]
      end

      unless new_valor.blank?
        extra.valor = new_valor
        extra.instancia = @instancia
        # Eliminar el valor viejo para poder terminar con un listado de
        # valores nuevos
        e.delete key
      end
    end

    # Agregar los extra nuevos
    @relevamiento.extras = @relevamiento.extras + process_extra(e, @instancia, new_fotos)
    # Actualizar el resto de parámetros
    @relevamiento.assign_attributes(p)
    # Guardar
    if @relevamiento.save
      render json: serialize(@relevamiento), status: :ok
    else
      render json: {}, status: :unprocessable_entity
    end

    # Eliminar las fotos temporales
    delete_fotos(new_fotos)
  end

  private

  def process_extra(extra, instancia, fotos = {})
    [extra.try(:to_hash).try(:map) do |n, v|
      Extra.new(plantilla_id: n.split('_').last.to_i, valor: v, instancia: instancia, fotos: fotos.dig(n))
    end].flatten.compact
  end

  def process_fotos(fotos)
    fotos.to_hash.map do |nombre, foto|
      next if foto.empty?
      # No confiamos en el tipo de imagen enviado en los metadatos,
      # decodificamos y luego comprobamos el tipo de datos
      data = Base64.decode64(foto.split(';base64,').last.strip)
      f = Tempfile.new(%w[image .tmp])
      f.binmode
      f.write(data)
      f.rewind
      f.close

      type = `/usr/bin/file --mime-type "#{f.path}"`.split(' ').last
      ext = type.split('/').last

      # Si es un archivo de imagen, devolver el archivo leido
      upload = nil
      if %w[jpg jpeg png].include? ext
        file = f.path.gsub(/\.tmp\Z/, ".#{ext}")
        FileUtils.mv(f.path, file)
        upload = File.open(file)
      end

      f.unlink
      { nombre => [upload] } if upload
    end.compact.reduce({}, :merge)
  end

  def delete_fotos(fotos)
    fotos.map { |n,f| File.unlink(f.first.path) }
  end

  def relevamiento_params
    params.require(:data)
      .require(:attributes)
      .permit(:descripcion, :direccion, :informacion_de_contacto,
        :categoria_id,
        :raiz_id,
        fotos: {},
        coordenadas: {},
        extra: {})
  end

  def serialize(relevamiento, *options)
    RelevamientoSerializer.new(relevamiento, *options).serialized_json
  end
end

app/controllers/panel/administradoras_controller.rb
class Panel::AdministradorasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    authorize Administradora
    @administradoras = policy_scope(Administradora)
  end

  def new
    authorize Administradora
    @administradora = Administradora.new
  end

  # Cuando creamos una administradora, no elegimos la contraseña sino
  # que le enviamos el correo de recuperación para que se elija una
  def create
    authorize Administradora
    @administradora = Administradora.new administradora_params
    @administradora.password = SecureRandom.hex

    if @administradora.save
      @administradora.send_reset_password_instructions
    end

    respond_with :panel, @administradora
  end

  # no necesitamos ver una pagina con el mail solamente
  def show
    redirect_to panel_administradoras_path
  end

  def destroy
    find_administradora
    authorize @administradora

    @administradora.destroy
    if @administradora == current_administradora
      sign_out
    else
      respond_with :panel, @administradora
    end
  end

  def edit
    find_administradora
    authorize @administradora
  end

  # Si cambiamos el mail le enviamos una notificacion
  def update
    find_administradora
    authorize @administradora

    @administradora.update_attributes administradora_params

    if @administradora.email_changed?
      @administradora.send_email_changed_notification
    end

    respond_with :panel, @administradora
  end

  def lock
    find_administradora
    authorize @administradora
    @administradora.lock_access! send_instructions: false

    respond_with :panel, @administradora
  end

  def unlock
    find_administradora
    authorize @administradora
    @administradora.unlock_access!

    respond_with :panel, @administradora
  end

  def super
    find_administradora
    authorize @administradora
    @administradora.super!

    respond_with :panel, @administradora
  end

  def unsuper
    find_administradora
    authorize @administradora
    @administradora.unsuper!

    respond_with :panel, @administradora
  end

  private

  def find_administradora
    @administradora = Administradora.find(params[:id] || params[:administradora_id])
  end

  def administradora_params
    params.require(:administradora).permit(:email, grupo_ids: [])
  end
end

app/controllers/panel/categorias_controller.rb
class Panel::CategoriasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    @categorias = policy_scope(Categoria)
  end

  def orden
    authorize Categoria
    if params[:categoria].blank?
      @categorias = Categoria.where(raiz_id: nil)
    else
      @categoria = Categoria.find(params[:categoria])
      @categorias = Categoria.where(raiz_id: params[:categoria])
    end
  end

  # Reordenar las categorías y subcategorías
  #
  # Al reordenar las categorías, necesitamos ubicar sub categorías justo
  # debajo de la categoría, recursivamente.
  def reordenar
    authorize Categoria
    p = params[:categorias][:orden]

    # Encontrar todas las categorías a ordenar, pueden ser raíz o sub
    # categorías o sub sub categorias
    @categorias = Categoria.where(id: p.keys)
    # Ejecutar dentro de una sola transacción
    Categoria.transaction do
      # Recorrerlas todas
      @categorias.each do |c|
        # Actualizar el orden a partir de la raíz y convertimos a un
        # decimal dentro de ese orden
        orden = if c.raiz
          c.raiz.orden + (p[c.id.to_s].to_f + 1.0) / Categoria::SUB_BASE
        # O si no hay raíz, usar un número entero.  Sumamos uno para no
        # empezar de 0
        else
          p[c.id.to_s].to_f + 1.0
        end

        # Actualizamos el orden
        c.update_attribute :orden, orden
        # Y también actualizamos el orden de las sub categorías
        c.sub_categorias.order(:orden).each_with_index do |s,i|
          s.update_attribute :orden, orden + (i.to_f + 1.0) / Categoria::SUB_BASE
        end
      end
    end

    redirect_to_filters_or panel_categorias_path
  end

  def new
    authorize Categoria
    @categoria = Categoria.new
    @categoria.raiz_id = params[:raiz] if params[:raiz].present?

    @categoria.color = "#%06x" % (rand * 0xffffff)
    @categoria.plantillas.build
  end

  def create
    authorize Categoria
    @categoria = Categoria.create categoria_params

    respond_with :panel, @categoria
  end

  # Por ahora no queremos ver ninguna categoría individual
  def show
    redirect_to_filters_or panel_categorias_path
  end

  def destroy
    find_categoria
    authorize @categoria
    @categoria.destroy
    respond_with :panel, @categoria
  end

  def edit
    find_categoria
    authorize @categoria

    @categoria.plantillas.build if @categoria.plantillas.empty?
  end

  def update
    find_categoria
    authorize @categoria
    @categoria.update_attributes categoria_params
    respond_with :panel, @categoria
  end

  private

  def categoria_params
    params
      .require(:categoria)
      .permit(:raiz_id, :nombre, :color, :descripcion, :confidencial,
        plantillas_attributes: [:id, :_destroy, :label, :help,
          :required, :photo, :value, :multiple, possible_values: [] ])
  end

  def find_categoria
    @categoria = Categoria.find(params[:id] || params[:categoria_id])
  end
end

app/controllers/panel/comentarios_controller.rb
class Panel::ComentariosController < ApplicationController
  before_action :authenticate_administradora!

  def create
    authorize Comentario
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.create(comentario_params)
    @comentario.comentarista = current_administradora

    @comentario.save

    redirect_to [:panel,@relevamiento]
  end

  def edit
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario
  end

  def update
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario

    @comentario.update_attributes comentario_params

    redirect_to [:panel, @relevamiento]
  end

  def destroy
    @relevamiento = Relevamiento.find(params[:relevamiento_id])
    @comentario = @relevamiento.comentarios.find(params[:id])
    authorize @comentario

    @comentario.destroy

    redirect_to [:panel, @relevamiento]
  end

  private
  def comentario_params
    params.require(:comentario).permit(:contenido, :privado)
  end
end

app/controllers/panel/extras_controller.rb
require 'csv'

class Panel::ExtrasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html, :csv, :geojson

  def index
    authorize Extra
    @q = policy_scope(Extra).includes(:plantilla, :instancia, relevamiento: [ :categoria ]).ransack(params[:q])
    @extras = @q.result
    @historico = params[:historico].present?

    respond_to do |f|
      f.html do
        @extras = @extras.page(params[:page])
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"extras.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }
        @headers = %w[id log_version relevamiento.categoria.arbol
          relevamiento.instancia.short_identifier relevamiento.id
          plantilla.label valor created_at updated_at]

        render layout: false
      end
    end
  end

  def historico
    authorize Extra
    @q = policy_scope(Extra).unscoped.includes(:plantilla, :instancia, relevamiento: [ :categoria ]).ransack(params[:q])
    # Agrupar los extras por relevamiento.  Ya vienen agrupados por
    # plantilla así que no es necesario.
    @extras = @q.result.sort_by do |e|
      e.plantilla.order
    end.group_by do |e|
      e.relevamiento_id
    end
    # Necesitamos saber la fecha mayor y menor
    @from = @q.result.order(:created_at).try(:first).try(:created_at)
    @to   = @q.result.order(:updated_at).try(:last).try(:updated_at)
    begin
      @range = (@from.try(:to_date)..@to.try(:to_date)).to_a
    rescue ArgumentError, TypeError
      @range = []
    end

    respond_to do |f|
      f.html do
      end

      f.csv do
        headers['Content-Disposition'] = "attachment; filename=\"historico.csv\""
        headers['Content-Type'] ||= 'text/csv; charset=utf-8'
        @headers = %w[relevamiento_id plantilla.label]
        @csv_options = { col_sep: ';', quote_char: '"', force_quotes: true }

        render layout: false
      end

      f.geojson do
        features = []

        # TODO esta algoritmo se repite por cada vista...
        @extras.each do |grupo|
          grupo.try(:last).try(:each) do |extra|
            attributes = {
              t('.relevamiento_id') => grupo.try(:first),
              t('.plantilla.label') => extra.try(:plantilla).try(:label)
            }.merge(
              Hash[@range.map do |date|
                [date, if extra.try(:updated_at).try(:to_date) == date
                  extra.try(:valor)
                else
                  extra.at(time: date).try(:valor)
                end]
              end])
            features << RGeo::GeoJSON::Feature.new(extra.relevamiento.coordenadas, extra.id, attributes)
          end
        end

        collection = RGeo::GeoJSON::FeatureCollection.new(features)

        render json: RGeo::GeoJSON.encode(collection)
      end
    end
  end

  def show
    @extra = policy_scope(Extra).find(params[:id])
    authorize @extra
  end

  def deshacer
    @extra = policy_scope(Extra).find(params[:extra_id])
    authorize @extra

    if @extra.switch_to! params[:version].to_i
      flash[:success] = t('.undo_success')
    else
      flash[:warning] = t('.undo_error')
    end

    redirect_to panel_extra_path(@extra)
  end
end

app/controllers/panel/grupos_controller.rb
class Panel::GruposController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def index
    @grupos = policy_scope(Grupo)
  end

  def new
    authorize Grupo
    @grupo = Grupo.new
  end

  def create
    authorize Grupo
    @grupo = Grupo.create(grupo_params)

    respond_with :panel, @grupo
  end

  def show
    authorize Grupo
    @grupo = Grupo.find(params[:id])
  end

  def edit
    authorize Grupo
    @grupo = Grupo.find(params[:id])
  end

  def update
    authorize Grupo
    @grupo = Grupo.find(params[:id])
    @grupo.update_attributes(grupo_params)

    respond_with :panel, @grupo
  end

  def destroy
    authorize Grupo
    @grupo = Grupo.find(params[:id])
    @grupo.destroy

    respond_with :panel, @grupo
  end

  private

  def grupo_params
    params.require(:grupo).permit(:nombre, administradora_ids: [], categoria_ids: [])
  end

end

app/controllers/panel/plantillas_controller.rb
class Panel::PlantillasController < ApplicationController
  before_action :authenticate_administradora!
  respond_to :html

  def orden
    @categoria = Categoria.find(params[:categoria_id])
    authorize @categoria, :ordenar_plantillas?
    @plantillas = @categoria.plantillas
  end

  def reordenar
    @categoria = Categoria.find(params[:categoria_id])
    authorize @categoria, :ordenar_plantillas?
    @plantillas = @categoria.plantillas

    order = params.require(:plantillas).permit(order: {})
    Plantilla.transaction do
      @plantillas.each do |p|
        p.update_attribute :order, order[:order][p.id.to_s]
      end
    end

    redirect_to_filters_or panel_categoria_plantillas_orden_path(@categoria)
  end
end

app/views/panel/relevamientos/edit.haml
.row
  .col
    = render 'panel/nav'
.row.justify-content-center
  .col-md-6
    .card
      %img.card-img-top{src: @relevamiento.fotos.first.try(:url) || '/default.png', alt: @relevamiento.descripcion}
      #map.minimap{data: { lat: @relevamiento.coordenadas.lat,
        lng: @relevamiento.coordenadas.lon,
        color: @relevamiento.categoria.color } }
    = form_for [:panel,@relevamiento], class: 'form' do |f|
      = hidden_field 'relevamiento[coordenadas]', 'lat'
      = hidden_field 'relevamiento[coordenadas]', 'lng'
      .form-group
        = f.label :fotos
        = f.file_field :fotos, multiple: true, class: 'form-control'
      .form-group.form-check
        = f.check_box :remove_fotos, class: 'form-check-input'
        = f.label :remove_fotos, class: 'form-check-label'
      .form-group
        = f.label :direccion
        = f.text_field :direccion, class: 'form-control'
      .form-group
        = f.label :descripcion
        = f.text_area :descripcion, class: 'form-control'
      .form-group
        = f.label :informacion_de_contacto
        = f.text_area :informacion_de_contacto, class: 'form-control'
      .form-group
        = f.label :categoria_id
        = f.collection_select :categoria_id, Categoria.all, :id, :arbol, {prompt: true}, { class: 'form-control' }
      .form-group
        = f.label :confirmado
        .form-check
          = f.check_box :confirmado, class: 'form-check-input'
          = f.label :confirmado, class: 'form-check-label'
      = f.fields_for :extras do |e|
        .form-group
          - case e.object.plantilla.try(:value)
            - when 'number'
              = e.label :valor, e.object.plantilla.try(:label)
              = e.number_field :valor, class: 'form-control'
            - when 'boolean'
              .form-check
                = e.check_box :valor, { class: 'form-check-input' }, 'true', 'false'
                = e.label :valor, e.object.plantilla.try(:label), class: 'form-check-label'
            - else
              = e.label :valor, e.object.plantilla.try(:label)
              = e.text_field :valor, class: 'form-control'
      .form-group
        = f.submit t('.submit'), class: 'btn btn-block btn-success'

app/views/panel/relevamientos/index.csv.erb
<%= "\xEF\xBB\xBF" %><%
csv = []
names = @headers.map { |h| t(".#{h}") }
names = names + @categoria.try(:plantillas).map(&:label) if @extras
csv << names
@relevamientos.to_a.uniq.each do |r|
  values = @headers.map do |h|
    begin
      r.instance_eval(h)
    rescue NoMethodError
      nil
    end
  end

  if @extras
    values = values + @categoria.try(:plantillas).try(:map) do |p|
      r.extras.to_a.find do |e|
        e.plantilla_id == p.id
      end.try(:valor)
    end
  end

  csv << values
end

%><%
csv.each do |row|
%><%=
  row.to_csv(@csv_options).html_safe
%><%
end
%>

app/views/panel/relevamientos/index.haml
.row
  .col
    = render 'panel/nav'
.row
  .col
    %h2= t('.filters')
    = search_form_for [:panel,@q] do |f|
      .row
        .col
          .form-group
            = f.label :categoria_id_eq
            = f.collection_select :categoria_id_eq, policy_scope(Categoria),
              :id, :arbol_con_total, {include_blank: true},
              {class: 'form-control select-2', placeholder: t('.prompt')}
            %small.form-text.text-muted= t(".categoria_help")
        .col-md-4
          .form-group
            = f.label :confirmado_eq
            = f.select :confirmado_eq,
              options_for_select([[t('.yes'),1],[t('.no'),0]], params.try(:q).try(:confirmado_eq).try(:to_i)),
              {include_blank: true},
              {class: 'form-control select-2', placeholder: t('.prompt')}
      .row
        .col
          - %w[extras sub_categorias].each do |checkbox|
            .form-check.form-check-inline
              = check_box_tag checkbox, 'true', params[checkbox].present?, class: 'form-check-input'
              %label{for: checkbox}
                = t('.'+checkbox)
                %small.form-text.text-muted= t(".#{checkbox}_help")
      .row.align-items-end
        .col
          .form-group
            = f.label :descripcion_cont
            = f.text_field :descripcion_cont, class: 'form-control'
        .col
          .form-group
            = f.label :informacion_de_contacto_cont
            = f.text_field :informacion_de_contacto_cont, class: 'form-control'
        .col
          .form-group
            = f.label :direccion_cont
            = f.text_field :direccion_cont, class: 'form-control'
      .form-group
        .row
          .col
            %button.btn.btn-info.btn-block{type: 'submit'}
              = fa_icon 'search'
              = t('.filter')
          .col-md-2
            = link_to panel_relevamientos_path(page: params[:page].try(:permit!)), class: 'btn btn-secondary' do
              = fa_icon 'remove'
              = t('.clear')
.row
  .col
    %h1
      = t('.title')
      = t('.results', q: @relevamientos.to_a.uniq.count)

    .btn-group
      - [[:csv, 'table', 'success'], [:geojson,'map-o','info']].each do |f|
        = link_to panel_relevamientos_path(format: f.first,
          q: params[:q].try(:permit!),
          page: params[:page].try(:permit!),
          extras: params[:extras],
          sub_categorias: params[:sub_categorias]),
          class: "btn btn-#{f.last}" do
          = fa_icon f.second
          = t(".#{f.first.to_s}")

    %table.table-striped.table.table-condensed.table-responsive
      %thead
        %tr
          %th= sort_link(@q, :id, '#')
          %th= sort_link(@q, :instancia, t('.instancia'))
          %th= sort_link(@q, :confirmado, t('.confirmado'))
          %th= sort_link(@q, :categoria_nombre, t('.categoria.nombre'))
          %th= sort_link(@q, :direccion, t('.direccion'))
          %th= sort_link(@q, :descripcion, t('.descripcion'))
          %th= sort_link(@q, :comentarios_count, t('.comentarios'))
          %th= sort_link(@q, :created_at, t('.created_at'))
          %th= sort_link(@q, :updated_at, t('.updated_at'))
          - if @extras
            - @categoria.try(:plantillas).try(:each) do |p|
              %th= p.try(:label)
          %th
      %tbody
        - @relevamientos.to_a.uniq.each do |r|
          %tr
            %td= link_to r.id, panel_relevamiento_path(r)
            %td= link_to r.instancia.short_identifier, panel_relevamientos_path(q: { instancia_id_eq: r.instancia.id })
            %td
              - if r.confirmado
                = fa_icon 'star'
            %td
              - if r.categoria.confidencial?
                = fa_icon 'lock', title: t('panel.categorias.fila.confidencial')
              = r.categoria
            %td= r.direccion
            %td= r.descripcion
            %td
              %ul
                - r.comentarios.each do |c|
                  %li
                    = c.contenido
                    = '--'
                    = c.comentarista
                    = c.created_at
                    = "(#{c.privado})"

            %td= r.created_at.strftime '%Y-%d-%m'
            %td= r.updated_at.strftime '%Y-%d-%m'
            - if @extras
              - @categoria.try(:plantillas).try(:each) do |p|
                -# La celda tiene que salir igual para no descompaginar las columnas
                %td
                  - if e = r.extras.to_a.find { |e| e.plantilla_id == p.id }
                    = e.valor
            %td
              .btn-group{role: 'group', aria: { label: t('.actions') }}
                = link_to edit_panel_relevamiento_path(r),
                  class: 'btn btn-secondary',
                  title: t('.edit') do
                  = fa_icon 'edit'
                = link_to panel_relevamiento_path(r),
                  method: :delete, class: 'btn btn-danger',
                  title: t('.destroy'),
                  data: { confirm: t('.destroy_confirm') } do
                  = fa_icon 'remove'
    = paginate @relevamientos, theme: 'twitter-bootstrap-4'

app/views/panel/relevamientos/show.haml
.row
  .col
    = render 'panel/nav'
.row.justify-content-center
  .col-md-8
    .card
      %img.card-img-top{src: @relevamiento.fotos.first.try(:url) || '/default.png', alt: @relevamiento.descripcion}
      .card-body
        %h5.card-title= @relevamiento.direccion || 'Relevamiento'
        %p.card-text= @relevamiento.descripcion
        %p.card-text= @relevamiento.informacion_de_contacto
        %p.card-text
          %span.badge{style: "background-color: #{@relevamiento.categoria.color}"}
            = @relevamiento.categoria

        %p.card-text
          - if @relevamiento.confirmado
            = fa_icon 'star'
            = t('.confirmed')
          - else
            = form_tag panel_relevamiento_confirm_path(@relevamiento), method: :post do |f|
              = button_tag class: 'btn btn-warning' do
                = fa_icon 'star'
                = t('.confirm')

        #map.minimap{data: { lat: @relevamiento.coordenadas.lat,
          lng: @relevamiento.coordenadas.lon,
          color: @relevamiento.categoria.color } }

        %table.table.table-condensed.table-striped.table-responsive
          %thead
          %tfoot
          %tbody
            - @relevamiento.extras.each do |extra|
              %tr
                %th= extra.plantilla.label
                %td= extra.valor
                %td
                  - unless extra.fotos.empty?
                    %a{href: extra.fotos.first.url}
                      %img.img-small{src: extra.fotos.first.thumb.url }

        %ul.list-group.list-group-flush
          - @relevamiento.comentarios.each do |comentario|
            %li.list-group-item
              .row
                .col
                  = comentario
                  %br/
                  %small.text-muted
                    - if comentario.privado?
                      = fa_icon 'lock'
                    = comentario.comentarista
                    = '--'
                    = comentario.created_at
                .col-2
                  .btn-group{role: 'group', aria: { label: t('.actions') }}
                    = link_to edit_panel_relevamiento_comentario_path(@relevamiento, comentario),
                      class: 'btn btn-secondary btn-sm',
                      title: t('.edit') do
                      = fa_icon 'edit'
                    = link_to panel_relevamiento_comentario_path(@relevamiento, comentario),
                      method: :delete, class: 'btn btn-danger btn-sm',
                      title: t('.destroy'),
                      data: { confirm: t('.destroy_confirm') } do
                      = fa_icon 'remove'
          %li.list-group-item
            = form_for [:panel,@relevamiento,@relevamiento.comentarios.build] do |f|
              .form-group
                = f.text_area :contenido, class: 'form-control', placeholder: t('.contenido')
              .form-check
                = f.check_box :privado, { checked: true, class: 'form-check-input' }
                = f.label :privado, class: 'form-check-label'
              .form-group
                = f.submit class: 'btn btn-success'